project:
  type: website

website:
  title: "Analyzing social scientists' testimonies trends before the United States Congress from 1946 to 2016"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



